// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTyZ8MoaLg6WJWY8O0KK9AxQavhNeATs',
    appId: '1:1035327393257:web:2e5bb69e7760f60ce08f78',
    messagingSenderId: '1035327393257',
    projectId: 'appointment-a324e',
    authDomain: 'appointment-a324e.firebaseapp.com',
    storageBucket: 'appointment-a324e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_5yvUa4pB7nvs1U7Eo2a-HdHWgrDyek',
    appId: '1:1035327393257:android:4e614ddfbe94a3c1e08f78',
    messagingSenderId: '1035327393257',
    projectId: 'appointment-a324e',
    storageBucket: 'appointment-a324e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5RoujlzqbwmNxwIkSHieg70amudiDzUM',
    appId: '1:1035327393257:ios:c3392831a0a1d386e08f78',
    messagingSenderId: '1035327393257',
    projectId: 'appointment-a324e',
    storageBucket: 'appointment-a324e.appspot.com',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5RoujlzqbwmNxwIkSHieg70amudiDzUM',
    appId: '1:1035327393257:ios:0d2f76cb4aa55271e08f78',
    messagingSenderId: '1035327393257',
    projectId: 'appointment-a324e',
    storageBucket: 'appointment-a324e.appspot.com',
    iosBundleId: 'com.example.appointment.RunnerTests',
  );
}
